# Generated by Django 3.1.5 on 2021-01-18 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店名')),
                ('genre', models.CharField(max_length=255, verbose_name='ジャンル')),
                ('location', models.CharField(max_length=255, verbose_name='所在地')),
                ('lat', models.FloatField(default=0, verbose_name='経度')),
                ('lng', models.FloatField(default=0, verbose_name='緯度')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
        ),
    ]
