# Generated by Django 3.1.5 on 2021-01-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapinfomodel',
            name='photo',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
